### ISSUE TITLE
IndexedDBStorage root can get out of sync in case of error

### ISSUE THREAD

**Issue by nedgar** [iden3/js-merkletree#22]
I noticed that [IndexedDBStorage#setRoot](https://github.com/iden3/js-merkletree/blob/main/src/lib/db/indexedDB.ts#L67) assigns the new root to `this.#currentRoot` before calling `async set(...)`. If the latter fails, then the field will be out of sync with storage. Suggest changing to:
```ts
  async setRoot(r: Hash): Promise<void> {
    await set(this._prefixHash, r, this._store);
    this.#currentRoot = r;
  }
```

FYI @Kolezhniuk

**Comment by Kolezhniuk** [comment]
Hello @nedgar good catch, I'll take a look
