### ISSUE TITLE
`delete` can't find the existing key

### ISSUE THREAD

**Issue by Arvolear** [iden3/js-merkletree#40]
Have been testing the SMT `delete` operation and encountered unexpected behavior in the following case:

```js
import { LocalStorageDB, Merkletree, str2Bytes } from "@iden3/js-merkletree";

import "mock-local-storage";

it("should remove elements from Merkle Tree correctly", async () => {
      const storage = new LocalStorageDB(str2Bytes(""));
      const localMerkleTree = new Merkletree(storage, true, 20);

      const keys = [7n, 1n, 5n];

      for (let key of keys) {
        await localMerkleTree.add(BigInt(key), key);
      }

      for (let key of keys) {
        await localMerkleTree.delete(BigInt(key));
        await localMerkleTree.add(BigInt(key), BigInt(key));
      }
});
```

The following code throws the error:

```bash
1) SparseMerkleTree
       Uint SMT
         should remove elements from Merkle Tree correctly:
     Error: the string "Key not found in the MerkleTree" was thrown, throw an Error :)
```

While the expected result is to succeed because I am just deleting and adding the same elements in place.

---

Package version: "@iden3/js-merkletree": "^1.2.0"
Node version: v18.18.0

**Comment by ilya-korotya** [comment]
Thanks for reporting the issue. We were able to reproduce this problem. It will take some time to fix it.

**Comment by ilya-korotya** [comment]
Hi @Arvolear. The latest commit to the main branch should fix the problem. Could you please check? Feel free to reopen the issue.

**Comment by Arvolear** [comment]
Will do. Thanks. If I encounter any divergence between [this](https://github.com/dl-solarity/solidity-lib/blob/master/contracts/libs/data-structures/SparseMerkleTree.sol#L791) Solidity implementation and the one in iden3, will let you know :)
